# Generated by Django 4.1.4 on 2022-12-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torqueapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Func",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=250)),
                ("disc", models.TextField()),
                ("img", models.ImageField(upload_to="gallery")),
            ],
        ),
    ]
