# Generated by Django 4.1.4 on 2023-01-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torqueapp", "0003_category_product_delete_contact_delete_func"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="available",),
        migrations.RemoveField(model_name="product", name="price",),
        migrations.RemoveField(model_name="product", name="stock",),
    ]
