# Generated by Django 4.1.4 on 2023-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torqueapp", "0004_remove_product_available_remove_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img1",
            field=models.ImageField(blank=True, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="img2",
            field=models.ImageField(blank=True, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="img3",
            field=models.ImageField(blank=True, upload_to="product"),
        ),
    ]
