# Generated by Django 4.1.4 on 2023-01-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torqueapp", "0005_product_img1_product_img2_product_img3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Func",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("disc", models.TextField()),
                ("year", models.IntegerField()),
                ("img", models.ImageField(upload_to="gallery")),
            ],
        ),
        migrations.RemoveField(model_name="product", name="category",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Product",),
    ]
