# Generated by Django 4.1.4 on 2023-01-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torqueapp", "0006_func_remove_product_category_delete_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="func",
            name="cust",
            field=models.CharField(default="aabb", max_length=250),
            preserve_default=False,
        ),
    ]
