# Generated by Django 4.1.4 on 2023-01-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torqueapp", "0008_func_img1_alter_func_cust"),
    ]

    operations = [
        migrations.AlterField(
            model_name="func", name="img1", field=models.ImageField(upload_to="photos"),
        ),
    ]
