# Generated by Django 4.1.4 on 2023-01-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torqueapp", "0009_alter_func_img1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("place", models.TextField()),
                ("mobile", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(model_name="func", name="img1",),
    ]
